### PR TITLE
Fix extra report folders creation

### LINKED ISSUE #1488: Extra report folders creation
Carina creates extra folders during run, because test report folder known only in one thread (private static final ThreadLocal<File> testDirectory = new ThreadLocal<File>(); in ReportContext) when driver do some actions in new thread, but connected with the same test. For example openURL in DriverHelper. There new thread created with Future<?> future = Executors.newSingleThreadExecutor().submit(new Callable<Void>() {}. Thats why every log in new thread is going to new report. and even if we delete all logs from call method, DriverListener also uses new thread and logs everything into new folder (screenshot from DriverListener goes to new folder too).

### PR DESCRIPTION
**Pull request by Eldarian**
Fixes #1488 

Added functionality that creates test report folder on test start manually. `testDirectory` is now `InheritableThreadLocal` variable. When there is a new thread created while test runs, initial value of `testDirectory` is the same as at the parent thread. 
ThreadLogAppender now checks does bufferedWriter logs to current test directory. 

Info logs work correctly, in debug log layer I found that some extra folders still arriving: for example, `OnAfterClass` (because TestLogAppender has already closed) and for running shutdown hook (because this log appears from special thread)

### CODE REVIEW

File: carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java [hunk 1]
```diff
@@ -473,6 +473,12 @@ public static void emptyTestDirData() {
         closeThreadLogAppender();
     }
 
+    public static void createNewTestDir() {
```
Comment (vdelendik) [inline carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java:476]: why do we need this method?

File: carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java [hunk 2]
```diff
@@ -128,7 +128,10 @@ public void onStart(ITestContext context) {
 
     @Override
     public void onTestStart(ITestResult result) {
+        // create new folder for test report
+        ReportContext.createNewTestDir(StringUtils.EMPTY);
```
Comment (vdelendik) [inline carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java:132]: 1. rename to createTestDir
2. implement 2 methods: one without args -> UUID for naming, and with actual parameter
